# tabs/professional_pdf.py
#
# A2: Extracted from base_tab.py to separate file.
# Custom PDF class with professional header/footer for report generation.
#
# Usage:
#   from tabs.professional_pdf import ProfessionalPDF
#   pdf = ProfessionalPDF(title, date_str, orientation='L', unit='mm', format='A4')

import os
from typing import Any

from fpdf import FPDF

from src.utils import resource_path, get_logger

logger = get_logger()


class ProfessionalPDF(FPDF):
    """Custom PDF class with professional header/footer for report generation."""

    def __init__(self, title_text: str, date_text: str, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.report_title = title_text
        self.report_date = date_text

    def header(self) -> None:
        # Logo (if exists)
        try:
            logo_path = resource_path("assets/logo.png")
            if os.path.exists(logo_path):
                self.image(logo_path, 10, 8, 12)
                self.set_x(25)  # Move text cursor after logo
        except Exception as e:
            logger.debug("Failed to load PDF logo: %s", e)

        # Title
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, self.report_title, 0, 1, 'L')

        # Date & Subtitle
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, f"Generated on: {self.report_date}", 0, 1, 'L')

        # Line break and horizontal rule
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 287, self.get_y())  # A4 Landscape width is ~297mm
        self.ln(6)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by NregaBot.com', 0, 0, 'C')
